[project]
name = "ssl101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flax",
    "optax",
    "jax[cuda12]",
    "ml-collections>=1.1.0",
    "orbax>=0.1.9",
    "dm-pix>=0.4.4",
    "augmax>=0.4.1",
    "wandb>=0.25.1",
    "gradio>=5",
    "pillow",
]

[dependency-groups]
dev = [
    "ruff>=0.15.11",
    "ty>=0.0.31",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.format]
quote-style = "double"

[tool.ty]

[tool.ty.environment]
python-version = "3.13"
